routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SessionsController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProductController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicio');
})->middleware('auth');

Route::get('/inicio', function () {
    return view('index');
});


Route::group(['prefix' => 'admin', 'as' => 'admin' ], function(){
    Route::get('/', [App\Http\Controllers\AdminController::class, 'index']);
    
});

Auth::routes();
Route::resource('/admin/products', ProductController::class);

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::post('register',[RegisterController::class,'store'])
    ->name('register.store');

Route::get('login',[SessionsController::class, 'create'])
    ->middleware('guest')
    ->name('login');


Route::post('login',[SessionsController::class,'store'])
    ->middleware('guest')
    ->name('login.store');

Route::get('logout',[RegisterController::class,'destroy'])
    ->middleware('auth')
    ->name('login.destroy');


Route::get('/admin', [AdminController::class, 'index'])
->middleware('auth.admin')
->name('admin.index');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Product
 *
 * @property $id
 * @property $Descripcion
 * @property $Precio
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Product extends Model
{
    
    static $rules = [
		'Descripcion' => 'required',
		'Precio' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['Descripcion','Precio'];



}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password){

        $this->attributes['password'] = bcrypt($password);
        
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index(){
        return view('admin');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

/**
 * Class ProductController
 * @package App\Http\Controllers
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate();

        return view('product.index', compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * $products->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = new Product();
        return view('product.create', compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Product::$rules);

        $product = Product::create($request->all());

        return redirect()->route('products.index')
            ->with('success', 'Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        request()->validate(Product::$rules);

        $product->update($request->all());

        return redirect()->route('products.index')
            ->with('success', 'Product updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $product = Product::find($id)->delete();

        return redirect()->route('products.index')
            ->with('success', 'Product deleted successfully');
    }
}

app/Http/Controllers/RegisterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class RegisterController extends Controller {
    
    public function create() {
        
        return view('auth.register');
    }

    public function store() {

        $this->validate(request(), [
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'required|confirmed',
        ]);

        $user = User::create(request(['name', 'email', 'password']));

        auth()->login($user);
        return redirect()->to('/');
    }
}

app/Http/Controllers/SessionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class SessionsController extends Controller {

    public function create() {
        return view('auth.login');
    }

    public function store() {
        if(auth()->attempt(request(['email', 'password'])) == false ) {
            return back()->withErrors([
                'message' => 'El email o la contraseña son incorrectos',
            ]);
        } else{
            if(auth()->user()->role == 'admin') {

                return redirect()->route('admin.index');
            } else {
                return redirect()->to('/');


            }
        }
    }

    public function destroy() {
        auth()->logout();

        return redirect()->to('/');
    }


    

}

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('template_title')
    Product
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Product') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Descripcion</th>
										<th>Precio</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $product)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $product->Descripcion }}</td>
											<td>{{ $product->Precio }}</td>

                                            <td>
                                                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('products.show',$product->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('products.edit',$product->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $products->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ShoppingFan</title>
  <!-- -------- anime css ------ -->
  <link rel="stylesheet" href="../../css/animate.css">
  <!-- --------- tiny slider css ------ -->
  <link rel="stylesheet" href="../../css/tiny-slider.css">
  <!-- --------- font awsome css ------ -->
  <link rel="stylesheet" href="../../css/all.css">
  <!-- -------- venobox css ------- -->
  <link rel="stylesheet" href="../../css/venobox.css" type="text/css" media="screen" />
  <!-- ---- Bootstrap css--- -->
  <link rel="stylesheet" href="../../css/bootstrap.min.css">
  <!-- ---------- default css --------- -->
  <link rel="stylesheet" href="../../css/default.css">
  <!-- --- style css -->
  <link rel="stylesheet" href="../../css/style.css">
</head>

<body>
  <!-- --------- preloader ------------ -->
  <div class="preloader">
    <div class="loader">
      <div class="spinner">
        <div class="spinner-container">
          <div class="spinner-rotator">
            <div class="spinner-left">
              <div class="spinner-circle"></div>
            </div>
            <div class="spinner-right">
              <div class="spinner-circle"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <!-------   Header star ------>
  <header class="header-area">
    <div class="navbar-area">
      <!---- navbar star--->
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
           <!--<a class="navbar-brand" href="#">
              <img class="images" src="../../assets/img/Shopping1.png" alt="">
            </a>-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                  <a class="nav-link active" data-scroll-nav="0" aria-current="page" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-scroll-nav="2" href="#about">Nosotros</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-scroll-nav="3" href="#">Subastas</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" data-scroll-nav="5" href="{{ route('login') }}">{{ __('Iniciar Sesion') }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-scroll-nav="6" href="{{ route('register') }}">{{ __('Registrarse') }}</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" data-scroll-nav="4" href="#">Contacto</a>
                </li>


              </ul>

            </div>
          </div>
        </nav>
      </div>
    </div>
    <!---- navbar end--->
    <div class="header-hero" data-scroll-index="0">
      <!---- home star ------>
      <div class="shape shape-1"></div>
      <div class="shape shape-2"></div>
      <div class="shape shape-3"></div>
      <div class="shape shape-4"></div>
      <div class="shape shape-5"></div>
      <div class="shape shape-6"></div>
      <div class="container">
        <div class="row align-items-center justify-content-center justify-content-lg-between">
          <div class="col-lg-6 col-md-10">
            <div class="header-hero-content">
              <h1 class="header-title wow fadeInLeftBig" data-wow-duration="2s" data-wow-delay="0.2s"><span>Bienvenido a ShoppingFAN</span></h1>
              <p class="text wow fadeInLeftBig" data-wow-duration="3s" data-wow-delay="0.4s">Vamos quién da más, ShoppingFan 
                te ofrece el mejor servicio de subastas online, ganar dinero se ha vuelto una manera mas divertida y segura
                por medio de sitios web.
              </p>
              <ul class="d-flex">
                <li><a href="" class="main-btn wow fadeInLeftBig" data-wow-duration="3s" data-wow-delay="0.8s">Comenzar...</a></li>
                
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="header-image">
              <img src="../../assets/img/7.png" alt="" class="image-1  wow fadeInRightBig"
                data-wow-duration="3s" data-wow-delay="0.5s">
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="header-shape-1"></div>
        <div class="header-shape-2">
          <img src="assets/img/header/header-shape-2.svg" alt="">
        </div>
      </div>
    </div>
    <!---- home star ------>
  </header>
  <!--------   Header End ----  -->

   <!-- ----------- About Section Start --------- -->
   <section class="about-area pt-70 pb-120" data-scroll-index="2" id="about">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="about-image wow fadeInLeftBig" data-wow-duration="2s" data-wow-delay="0.5s">
            <div class="about-shape"></div>
            <img src="../../assets/img/commpra.png" alt="" class="app">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="about-content mt-50 wow fadeInRightBig" data-wow-duration="3s" data-wow-delay="0.5s">
            <div class="section-title">
              <h1 class="title">Acerca de Nosotros</h1>
              <p class="text">Nuestra empresa Shopping Fan esta dirigida a todas aquellas personas 
                que desean realizar subastas de diferentes articulos, haciendo que el
                proceso sea más facil mediante la innovación tecnologica.
              </p>

              <p class="text">Nuestra empresa Shopping Fan esta dirigida a todas aquellas personas 
                que desean realizar subastas de diferentes articulos, haciendo que el
                proceso sea más facil mediante la innovación tecnologica.
              </p>
            </div>
            <a href="" class="main-btn">Leer más</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ----------- About Section End --------- -->

  <!-- --------------Footer Section Start ------- -->
  <footer class="footer-area">
    <div class="footer-shape shape-1"></div>
    <div class="footer-shape shape-2"></div>
    <div class="footer-shape shape-3"></div>
    <div class="footer-shape shape-4"></div>
    <div class="footer-shape shape-5"></div>
    <div class="footer-shape shape-6"></div>
    <div class="footer-widget pt-30 pb-80">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="footer-about mt-50">
              <a href="" class="logo">
                <img src="assets/img/header/logo/landapp-logo.png" alt="">
              </a>
              <p class="text">Día con día shoppingfan puede ser tu mejor aliado para subastar los articulos que desees</p>
              <ul class="social">
                <li><a href=""><i class="fab fa-facebook-f"></i></a></li>
                <li><a href=""><i class="fab fa-twitter"></i></a></li>
                <li><a href=""><i class="fab fa-instagram"></i></a></li>
                <li><a href=""><i class="fab fa-linkedin-in"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-5 col-md-6">
            <div class="footer-link d-flex flex-wrap">
              <div class="footer-link-wrapper mt-45">
                <div class="footer-title">
                  <h4 class="title">Quick Links</h4>
                </div>
                <ul class="link">
                  <li><a href="">Home</a></li>
                  <li><a href="">Features</a></li>
                  <li><a href="">About</a></li>
                  <li><a href="">Testimonial</a></li>
                  <li><a href="">Pricing</a></li>
                  <li><a href="">Download</a></li>
                </ul>
              </div>
              <div class="footer-link-wrapper mt-45">
                <div class="footer-title">
                  <h4 class="title">Support</h4>
                </div>
                <ul class="link">
                  <li><a href="">FAQ</a></li>
                  <li><a href="">Privacy Policy</a></li>
                  <li><a href="">Terms OF Use</a></li>
                  <li><a href="">Legal</a></li>
                  <li><a href="">Site Map</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="footer-contact mt-45">
              <div class="footer-title">
                <h4 class="title">Quick Links</h4>
              </div>
              <ul class="contact-list">
                <li>
                  <div class="contact-info">
                    <div class="info-content media-body">
                      <p class="text"><i class="fas fa-phone-alt"></i>
                        +6182319469 </p>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="contact-info">
                    <div class="info-content media-body">
                      <p class="text"><a href=""><i class="far fa-envelope"></i>
                          ShoppingFan@gmail.com </a></p>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="contact-info">
                    <div class="info-content media-body">
                      <p class="text"><a href=""><i class="fas fa-globe"></i>
                          www.Shopping.com </a></p>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="contact-info">
                    <div class="info-content media-body">
                      <p class="text"><i class="fas fa-map-marker-alt"></i>
                        123 stree now york city, united states of america 750 </p>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        <div class="row justify-content-center">
          <div class="lo-lg-12">
            <div class="copyright">
              <div class="copyright-text text-center">
                <p class="text">Copyright &#169; 2020 <a href="">ShoppingFan</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>


    <!-- ---- jquery Js ---- -->
    <script src="../../js/jquery-1.12.4.min.js"></script>
    <!-- -------- venobox js ------ -->
    <script type="text/javascript" src="../../js/venobox.min.js"></script>
    <!-- ---------- wow js ---------- -->
    <script src="../../js/wow.min.js"></script>
    <!-- ---------- tiny slider js --------- -->
    <script src="../../js/tiny-slider.js"></script>
    <!-- ---------- scrollit js ---------- -->
    <script src="../../js/scrollIt.min.js"></script>
    <!-- -------- font awsome js --------- -->
    <script src="../../js/all.js"></script>
    <!-- ---- Bootstrap Js ---- -->
    <script src="../../js/bootstrap.min.js"></script>
    <!-- ---- main js --- -->
    <script src="../../js/main.js"></script>

resources/views/inicio.blade.php
@extends('layouts.app')

@section('content')
    
<h1>BIENVENIDO A SHOPPINGFAN</h1>
@endsection

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ShoppingFan</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item">
        <a class="nav-link" href="/admin/">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Admin</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="/admin/products">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Productos</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="/admin/inventario">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Inventario</span>
        </a>
    </li>

</ul>

resources/views/product/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Product
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Product</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('products.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('product.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Product
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Product</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('products.update', $product->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('product.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/product/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('Descripcion') }}
            {{ Form::text('Descripcion', $product->Descripcion, ['class' => 'form-control' . ($errors->has('Descripcion') ? ' is-invalid' : ''), 'placeholder' => 'Descripcion']) }}
            {!! $errors->first('Descripcion', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Precio') }}
            {{ Form::text('Precio', $product->Precio, ['class' => 'form-control' . ($errors->has('Precio') ? ' is-invalid' : ''), 'placeholder' => 'Precio']) }}
            {!! $errors->first('Precio', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/product/index.blade.php
@extends('layouts.app')

@section('template_title')
    Product
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Product') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Descripcion</th>
										<th>Precio</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $product)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $product->Descripcion }}</td>
											<td>{{ $product->Precio }}</td>

                                            <td>
                                                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('products.show',$product->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('products.edit',$product->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $products->links() !!}
            </div>
        </div>
    </div>
@endsection